sudo: false

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install codecov

script:
  - python -m unittest discover -p "*_test.py"
  - coverage run -m unittest discover -p "*_test.py"

after_script:
  - codecov
