sudo: false

language: python
python: "3.7"

install:
  - pip install codecov

script:
  - python -m unittest discover -p "*_test.py"
  - coverage run -m unittest discover -p "*_test.py"

after_script:
  - codecov
