sudo: false

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install codecov
  - pip install setuptools
  - pip install .

script:
  - python -m unittest discover -b -p "*_test.py"
  - coverage run -m unittest discover -b -p "*_test.py"

after_script:
  - codecov
